### ISSUE TITLE
[Text Input] Pressing Shift+Enter should insert a new line/carriage return, instead of sending the message

### ISSUE THREAD

**Issue by nyanpasudo** [gokiburikin/nyanpals#17]
This allows multi-line messages to be sent in a single message

**Comment by gokiburikin** [comment]
implemented in https://github.com/gokiburikin/nyanpals/commit/e871486dba9f7ba5bc39ad86a397fc64be380ee7

**Comment by Kyuturu** [comment]
I'll write a new ticket for the expanding input box for tracking
